# -*- coding: utf-8 -*-
"""Tensor flow

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-jX1Ji_Fec93jEAB-eC5KNRX7hS1L1Nz
"""

pip install tensorflow

import tensorflow as tf

import pandas as pd

import numpy as np

tf.constant([100,200,300.400])

c=tf.constant([100,200,300,400])

c

print(c)

sc=tf.constant(500)

sc

f= tf.constant(21.23)

f

s= tf .constant("welcome to tenserflow class")

s

cp=tf.constant(10+4j)

cp

a=10
b=20
c=30
var = tf.constant([a,b,c])

var

var.shape

var.ndim

var.dtype

tf.constant([a,b,c],dtype='float64')

tf.constant([10,20,30,40,50,60],dtype='float32')

tf.constant([10,20,30,40,50,60],shape=(3,2),dtype=tf.float64)

nlist = [[10,20,30],[100,200,300,],[1,2,3]]

nlist

tf.constant(nlist)

ary1=np.random.randint(10,200,(4,6))

ary1

np_const = tf.constant(ary1, dtype = tf.float64)

np_const

print(np_const)

tf.print(np_const)

df1=pd.DataFrame(ary1)

df1

tf.constant(df1)

tf.zeros((4,5))

tf.zeros(shape=(4,5))

tf_zeros = tf.zeros(shape=(4,5),dtype=tf.int32)

tf_zeros

tf.print(tf_zeros)

tf1 = tf.ones(shape=(4,5),dtype = tf .int32)

tf1

tf.eye(5)

tf.range(10,20,1)

tfc1= tf.range(1,6)

tfc1

tfc1

tfc1.shape

